name: triviados
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  equatable: ^0.4.0
  dependencies_flutter: ^0.1.6
  flutter_bloc: ^2.1.1
  dio: ^3.0.7
  http: ^0.12.0+2
  data_connection_checker: ^0.3.4
  shared_preferences: ^0.5.4+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0


# The following section is specific to Flutter.
flutter:

  uses-material-design: true